#!/bin/bash

MARITACA_MOBILE_APPS="$1"
PACKAGE_NAME="$2"
ANDROID_PATH="$3"
PROJECT_NAME="maritaca-mobile"
DIR_NEW_PROJECT=$MARITACA_MOBILE_APPS/$PACKAGE_NAME
cd $DIR_NEW_PROJECT/$PROJECT_NAME
ant release -Dsdk.dir=$ANDROID_PATH
